#use_frameworks!

platform :ios, '12.0'

target 'MixPod_Example' do
  pod 'MixPod', :path => '../'
  pod 'OCPod', :path => '../../OCPod'
  pod 'SwiftPod', :path => '../../SwiftPod'
  
  target 'MixPod_Tests' do
    inherit! :search_paths
    
  end
end
